### ISSUE TITLE
Sort by additional metadata

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#60]
- name
- TDU
- file changed date

File changed data is interesting and also hints of use cases where any of this metadata could be used to sort or filter.

**Comment by tparchambault** [comment]
@jw3 Currently all visible columns(including mTime) are sortable. The only permutation that I can see to keep this ticket open might be to have separate sortable columns for basename and dirname. Another option would be to add another sortable column for basename only and leave the current absolute path column as is.

Otherwise, unless I'm not considering something here, this can be closed.
