### ISSUE TITLE
Profiler must have valid target to start

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#632]
1. Open profiler
2. Click Start Test
3. Observe that the system switches fapolicyd, incurring the delay, and prints fapolicyd log file to text view, all while the actual profiling is doomed to failure because there is no executable.

Check the target and ensure it
1. Is a file
2. Is executable

I think waiting until the start button is clicked is fine, but it should do the check and fail fast.

**Comment by tparchambault** [comment]
Will add backend code to check if executable is  not null and is valid. Will also look at modifying the toolbar 'run' btn widget to be dimmed if exec field is empty.

**Comment by tparchambault** [comment]
I was originally going to implement this w/exceptions generated by the Profiling Session's consturctor when invalid arguments are supplied at instantiation. I decided to return None if the session creation fails, and create static class methods that validate arguments and in the case of an invalid argument provide both bool pass/fail classifications and error specifics. The availability of these validation functions mean that arguments can be validated at either the UI level or the Profiler Session class levels.

If checked at the UI level and invalid arguments are detected, the appropriate edit field or text feedback can be immediately displayed and/or highlighted, allowing the user the opportunity to correct their input immediately. This approach seemed  more appropriate for controlling a UI input loop vs exception handling.

**Comment by tparchambault** [comment]
Ummm, never-mind... Still going to create static validation functions so that the UI layer can leverage them for error feedback, _but_ returning `None` when creating the FaProfSession` appears to involve doing validation checks inside the `__new__()` function when the object is allocated, prior to when `__init__()` is invoked. It would be adding complexity for very little gain; This is when I miss C++ and the ability to override an object's `new()` function and use explicit `malloc()s`. C'est la vie.

**Comment by jw3** [comment]
#656
