### ISSUE TITLE
Profiler executable argument validaiton should consider PATH env

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#655]
The profiler will not allow non-absolute paths to be used as the executable.  The expectation is that the PATH in the environment (either specified or inherited) would be used when looking for the executable.

For example use `ls` as the target will fail,  you instead must use absolute path of  `/bin/ls`.
The validation should consider whatever path the execution is going to use when validating the path variable.

This is a regression from #640 

Blocking release of v0.6.1

**Comment by tparchambault** [comment]
Agreed. Will incorporate PATH of pkexec environment and any PATH specified in the profiler's UI env var field when working with relative exec paths.

**Comment by tparchambault** [comment]
, I still need to write some regex code to detect "$PATH" and replace it with os.getenv("PATH") and verify leading, trailing, and double colons map to pwd for those times the user expects the environment field's PATH handling to align with that of the shell before this ticket is considered done, I'm betting that some function in either the shutil or os modules with provide that expansion. If not, I heart regex.

Fwiw: In the pkexec environment, PATH=/usr/sbin:/usr/bin:/sbin:/root/bin

That's got to get documented somewhere or we could pre-populate the env var field with it already assigned to PATH. Otherwise, the user would be guessing; They've got to be made aware that their current user PATH will differ from that of the Profiler.

Or, we could just set the PATH env var to that of either 'sudo su' or 'sudo su -' programmatically.

For now, we are going with pkexec's default PATH: "/usr/sbin:/usr/bin:/sbin:/root/bin" if the PATH specified via the profiler's env var field is omitted.
