### ISSUE TITLE
Rule editor validation disabled

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#687]
When editing rules the validation button seems to detect state incorrectly and will not become enabled.

1. load rules
2. add a typo
3. click validate
4. remove the typo
5. observe that the validate button is not enabled

**Comment by dorschs57** [comment]
@jw3 This happens because when you revert back the text is no longer dirty and does not need to be saved. example with rule `allow perm=any all : all`

1. change perm to `foo`
2. validate and save button are enabled
3. change perm back to original `any`
4. validate and save button are disabled
5. change perm to `foo`
6. validate and save buttons are enabled
7. change perm to `open`
8. validate and save buttons remain enabled

We are comparing the updated text with the original captured during the load time to test for dirty text and enable or disable.

**Comment by jw3** [comment]
> the text is no longer dirty and does not need to be saved

Right, not saved, just validated.

When validate fails it adds an error to the status tree, I would expect to validate again after undoing that change to remove it.
