### ISSUE TITLE
Upgrade Webkit to 4.1

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#903]
https://bugzilla.redhat.com/show_bug.cgi?id=2232959

See #824

**Comment by jw3** [comment]
Temporary issue resolved when webkit was packaged.

**Comment by jbicha** [comment]
It would be great if this app would stop using the webkitgtk 4.0 API but use 4.1 instead (which is the same as 4.0 but uses libsoup3 instead of libsoup2.4).

See https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version

[webkit2gtk4.0](https://packages.fedoraproject.org/pkgs/webkit2gtk4.0/) was packaged for Fedora 40 as hopefully a temporary workaround to give packages a bit more time to adapt.

**Comment by jw3** [comment]
@jbicha thanks for the heads up. I'll take a look at this.
